((nil . ((projectile-project-compilation-dir . "<build_dir>")
         (projectile-project-configure-cmd . "<configure_cmd>")
         (projectile-project-compilation-cmd . "<compilation_cmd>")
         (projectile-project-run-cmd . "<run_cmd>")
         (projectile-project-test-cmd . "<test_cmd>")
         )))
